### ISSUE TITLE
Where are the other chapters? 

### ISSUE THREAD

**Issue by kimberly-bastille** [NOAA-EDAB/tech-doc#104]
I am looking for the SST climatologies and https://noaa-edab.github.io/tech-doc/index.html only shows the intro. Where are the chapters stored and is there a link in the tech doc intro that I am missing?

**Comment by sgaichas** [comment]
I did notice this morning that links are broken but can't see why, there have been no changes to the main branch. strange...

**Comment by andybeet** [comment]
This is temporary. Should be back up today. The site builds from master and dev (which is where changes are being made)
The format of the book has changed and it appears some of the bookdown syntax has changed too.
But it is building locally so should be back up soon @BBeltz1

**Comment by BBeltz1** [comment]
@andybeet @kimberly-bastille @sgaichas this is correct. should be up soon. there are some linux-specific syntax issues that i am reconciling now. after which the book should rebuild to its usual state. sorry for the inconvenience!

**Comment by BBeltz1** [comment]
@sgaichas @kimberly-bastille @andybeet tech doc is back online now. please pardon the dust, there are some weird artifacts from the reformatting we've done. i will be cleaning these things up as i find them. thanks for the patience.

**Comment by kimberly-bastille** [comment]
Thanks all! Love the panel sections btw.
