### ISSUE TITLE
Change repo name...

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/tech-doc#37]
to tech-doc to better reflect the "technical documentation" name that we're going forward with. Does anyone have any reservations about changing the name? I'd rather do it before we submit to IR.

**Comment by slucey** [comment]
Fine with me


Sean M. Lucey
Fisheries Biologist
Ecosystem Dynamics and Assessment Branch
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)

**Comment by sgaichas** [comment]
OK with me too.

**Comment by slarge** [comment]
I'll do later this afternoon, will need to do find and replace for some links.

**Comment by seanhardison1** [comment]
Works for me too.

**Comment by slarge** [comment]
Hi gang, 
 I've just gone through and changed the tech-memo mentions throughout the tech-doc. I haven't been able to build the document (only trying to knit using index.Rmd, not sure what the process should be)
