### ISSUE TITLE
add how-to vignette for updating tech-doc

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/tech-doc#56]
needed so that any of us can update this in coming years
outline

- tech-doc is not like our other repos because it uses Travis-CI.

    - this means we don't pull, build locally, and push all to master.

    -  instead we only edit rmd files and push those to master, letting Travis do the build.

- there is a need to check build status and diagnose errors on Travis (show how to do)

- major structural changes to repo folders change how books can be built and should be discussed prior to implementation, with documentation of changes

- other points to be discussed

**Comment by kimberly-bastille** [comment]
[Wiki outlining GitHub Actions](https://github.com/NOAA-EDAB/tech-doc/wiki/GitHub-Actions) use to build and deploy the book.
