### ISSUE TITLE
_bookdown.yml options and implications

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/tech-doc#57]
When all .Rmd files were in master directory, we used the following options
```
delete_merged_file: true
new_session: yes
```

I think this meant individual .Rmds were knitted in their own sessions. this kept them independent (so one failing didn't break the whole book?), but necessitated setup blocks in each with libraries, etc. these setup blocks are part of the documentation.

the current options are 
```
delete_merged_file: false
new_session: no
```

The false option for delete merged file means when I build locally for testing I get errors due to the old merged file still existing. I can change this back to true locally without affecting anything. My guess is that we have this option so that the old merged file still shows online if a new Travis build fails? 

- need to understand advantages and implications of `delete_merged_file: false`

`new_session: yes` no longer works since .Rmds are not in the master directory. Code blocks with r packages are now set to eval=F so that they show up in the doc. I think this means all r packages are listed in the index.Rmd setup block--important to remember this when adding chapters.

- need to understand advantages and implications of `new_session: no`

please document discussion and add to how-to vignette (issue  #56) before closing

**Comment by kimberly-bastille** [comment]
Issue #56 Closed with wiki on github actions added. 

Current workflow includes `delete_marged_file: false` and `new_session: false` in the `_bookdown.yml`. With each push, the GitHub action builds the full book from scratch.
