### ISSUE TITLE
_output.yml options to fix broken pdf link

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/tech-doc#58]
Options for pdf book do not correctly assign the bookdown link to the pdf in repository (it should be in the _book directory, but link points to master directory, and still doesn't work when the _main.pdf is placed there). Current code at the end of _output.yml:

```
bookdown::pdf_book:
  keep_tex:  yes
```
Online suggestions address the issue [when implementing from a docs folder](https://community.rstudio.com/t/download-pdf-icon-in-bookdown/33118) but we are implementing from a gh-pages branch via Travis so our situation is different.

When solved, document in how-to vignette  (issue #56)

**Comment by kimberly-bastille** [comment]
The pdf is built by travis using the code below in the [.travis.yml](https://github.com/NOAA-EDAB/tech-doc/blob/master/.travis.yml). PDF can be [downloaded here](https://noaa-edab.github.io/tech-doc/tech_doc.pdf) so there is no need to build local. 

```
script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
```
