### ISSUE TITLE
NE_HABs_indicator.Rmd crop error

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/tech-doc#59]
When building locally on macOS, _main.Rmd fails at lines 5513-5591 with a Topology Exception

Local testing isolates the error to line 123 of NE_HABs_indicator.Rmd:
```
> coast1 <- crop(coast, e1)
Error in RGEOSBinTopoFunc(spgeom1, spgeom2, byid, id, drop_lower_td, unaryUnion_if_byid_false,  : 
  TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -76.471141840000001 37.320285419999998 at -76.471141840000001 37.320285419999998
```

All files were pulled from tech-doc repo so perhaps there is something missing?

**Comment by kimberly-bastille** [comment]
Now that tech doc builds to both HTML and PDF. It should not be necessary to build locally.
