### ISSUE TITLE
Comlands code

### ISSUE THREAD

**Issue by kimberly-bastille** [NOAA-EDAB/tech-doc#62]
Link to comlands package when it is finished. For now the code is linked within tech doc as other chapters without public code.

**Comment by kimberly-bastille** [comment]
@slucey @andybeet can you guys point to where in comlandr [this code](https://github.com/NOAA-EDAB/tech-doc/blob/master/R/stored_scripts/landings_extraction.R) lives or is it best if I just link to the whole package?

**Comment by andybeet** [comment]
@kimberly-bastille This code IS the comlandr package. The script has just been split up into sub functions
It is still in development, but you should point to it https://github.com/NOAA-EDAB/comlandr
Hopefully we'll have is squared away in a week or two.

**Comment by kimberly-bastille** [comment]
fixed with commit 1403adc5e103dee57e28ac0c83841490f254dd27
