### ISSUE TITLE
travis migration

### ISSUE THREAD

**Issue by kimberly-bastille** [NOAA-EDAB/tech-doc#63]
Large scale migration from travis-ci.org to travis-ci.com is underway and tech doc is still on travis-ci.org.  It will still work for now, but I think we should manually make the transition soon.  It looks like it is only a few steps according to [docs](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg) but it may need to be the creator (@sgaichas) who initiates the migration. 

More explanation of the [difference](https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com).

**Comment by sgaichas** [comment]
Migration initiated 26 March 20202. Holding breath to see if this worked.

**Comment by sgaichas** [comment]
build failing at ecodata installation
```
Error in loadNamespace(name) : there is no package called ‘ggplot2’
Error: unable to load R code in package ‘ecodata’
Execution halted
ERROR: lazy loading failed for package ‘ecodata’
* removing ‘/home/travis/R/Library/ecodata’
Error: Failed to install 'ecodata' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpBd9bza/file42005ac107e0/ecodata_0.1.0.tar.gz’ had non-zero exit status
Execution halted
```

**Comment by kimberly-bastille** [comment]
Build Fixed commit  7ab36d
