### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/tech-doc#64]
@kimberly-bastille what is the best way to build a figure in one of these chapters?  I want to add the new strata/epu map and am not sure if I should just import my code or if loading a pre-made figure is easier.  If the first, I'll need to know where to put the shapefiles.

**Comment by kimberly-bastille** [comment]
I haven't been able to get maps to work smoothly from code with Travis so I store them in [images](https://github.com/NOAA-EDAB/tech-doc/tree/master/images) and then include them using the code below. 

```{r map-x, fig.cap="Add relevant caption."}
knitr::include_graphics(file.path(image.dir, "map-x.png"))
```

**Comment by slucey** [comment]
OK...will upload the image then.
