### ISSUE TITLE
Filling out a section from scratch

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/tech-doc#65]
@kimberly-bastille is the documentation about what we are looking for in each section available?

**Comment by kimberly-bastille** [comment]
We do not have that but we definitely should. In the [data delivery form](https://docs.google.com/forms/d/e/1FAIpQLSdzqc6lcA83tPCl21t24VL7ODgHV362HDua5Qey-OhW2G7iMg/viewform) there are sections corresponding to each tech doc section within a chapter but I don't think that is enough. I will work up a draft.

**Comment by kimberly-bastille** [comment]
Here is the first draft of the [chapter prompt](https://github.com/NOAA-EDAB/tech-doc/blob/master/chapters/chapter_prompt.Rmd). It is pretty basic so please look through and give notes. @slucey @slarge @sgaichas @khyde @gdepiper

**Comment by kimberly-bastille** [comment]
Here is a [google-doc version](https://docs.google.com/document/d/1DgAEQmrx4fNCGyQxiNgJgkHORC0dar_tJrB4mtZuQg0/edit) so we can collaborate with people outside of Github. Note that the only sections that need contributors attention are those highlighted in red.
