### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by kimberly-bastille** [NOAA-EDAB/tech-doc#66]
The line endings between difference systems are creating issues with tracking changes between commits. 

[.gitattributes](https://github.com/NOAA-EDAB/tech-doc/blob/master/.gitattributes) added to fix this using advice from [help.github](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) but since that change we are still having issues between Windows and Linux. 

@sgaichas is this happening if you pull from Mac?

@bbest is this something you have run across before?

**Comment by slucey** [comment]
@kimberly-bastille I just pushed the SAFMC species chapter back on to the repo and it seems to have tracked the changes.  I then nuked my local copy and recloned.  Can you change something to that file and we'll test this again.

**Comment by kimberly-bastille** [comment]
So the changes were correct when I pulled your edits and the push was clean too.

**Comment by slucey** [comment]
Seems to have worked...for now.  Maybe we needed one more push pull to renormalize on my end.

**Comment by kimberly-bastille** [comment]
Strange though because you had multiple commits since I added the .gitattributes so you must have had some pull/push activity to normalize. Were those commits from changes made in the github interface? or did you push from your local machine?

**Comment by slucey** [comment]
I had pushed from my local machine.  No idea what happened...

**Comment by kimberly-bastille** [comment]
We should come up with directions for what to do if this happens again. Or add a note about this in our "how we work" documentation.

**Comment by kimberly-bastille** [comment]
Added [how we work wiki](https://github.com/NOAA-EDAB/tech-doc/wiki/How-we-work) outlining the collaboration process for tech doc. Includes notes on past issues and possible solutions.
