### ISSUE TITLE
Le Cren reference

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/tech-doc#77]
https://github.com/NOAA-EDAB/tech-doc/blob/bcdeb2068ef38dbb04cc517f50d3393921b96fe4/bibliography/Condition.bib#L17

The citation should be for Le Cren 1951. I think the following should fix it:

author = {Le Cren, E. D.},

**Comment by kimberly-bastille** [comment]
Fixed in commit [6ac8216](https://github.com/NOAA-EDAB/tech-doc/commit/6ac8216de4975017e37991536807b11305a58855)
